# Netlify Configuration
[build]
  publish = "frontend/.next"
  command = "cd frontend && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy (se usando Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://your-backend-api-url.com"

# Environment variables for deploy preview
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  NEXT_PUBLIC_API_URL = "https://your-staging-backend-url.com"